name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "NOTES", id = "da46d97ff80a4cfe8afd3daf0157e092", preview_id = "da46d97ff80a4cfe8afd3daf0157e092" },
  { binding = "SHARE", id = "64bd8d3fed134e3a81e4b0d7c76fbd58", preview_id = "64bd8d3fed134e3a81e4b0d7c76fbd58" }
]

[env.production]
kv_namespaces = [
    { binding = "NOTES", id = "da46d97ff80a4cfe8afd3daf0157e092" },
    { binding = "SHARE", id = "64bd8d3fed134e3a81e4b0d7c76fbd58" }
]